#!/usr/bin/env python3
from __future__ import annotations

import argparse
import asyncio
import json

from app.forecasting.training import train_random_forest_forecaster


def parse_args():
    parser = argparse.ArgumentParser(description="Train the MarketMetrics stock forecasting model.")
    parser.add_argument(
        "--symbols",
        nargs="*",
        default=None,
        help="Optional list of ticker symbols to train on. Defaults to the curated catalog universe.",
    )
    parser.add_argument(
        "--version",
        default=None,
        help="Optional model version label. Defaults to an autogenerated timestamp version.",
    )
    parser.add_argument(
        "--lookback-days",
        type=int,
        default=None,
        help="Historical lookback window in days for the training dataset.",
    )
    return parser.parse_args()


async def main():
    args = parse_args()
    metadata = await train_random_forest_forecaster(
        symbols=args.symbols,
        version=args.version,
        lookback_days=args.lookback_days,
    )
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    asyncio.run(main())
